services:
  - type: web
    name: storychain-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: RECEIVER_ADDRESS
        sync: false
      - key: PORT
        value: 3000
